---
title: "Final Grade Reflection"
author: "Allen Choi"
format: pdf
editor: visual
---

I believe that so far I earned an A- in this course. WD-1 was demonstrated in Lab 2 #1. WD-2 was demonstrated in

In terms of learning targets, I believe that Challenge 4 demonstrated all the learning targets from WD-1 to WD-6.: I imported a csv file, used select to pick the city columns that I wanted, filtered for four specific years that I needed, used filtering joins to select avocados only from four specific cities, and then combined a dataframe containing housing data with another dataframe containing avocado sales data using a mutating join.

In terms of reproducibility, all of my assignments including Lab 5, Challenge 3, and Challenge 4 use the here package. I try to make my code as professional as possible by not including the warning message as shown in Lab 5. I am still in the process of achieving R-2 since I don't really document my code, though for R-3 I use column names instead of their positions to make them resistant to input changes. For showcasing the learning targets for data visualization, I believe that Lab 5 is a good example for DVS-1 to DVS-2: I created a visualization for categorical data vs. quantitative data with the time series plot, and used plot modifications to get rid of the y-axis title and moved the title to the left. I showed creativity in my visualizations in Challenge 2 where I added color in order to spice up the graph. For DVS-4 to DVS-5 Lab 5 is a good example when I calculated means across year and genus. In Challenge 3 I demonstrated that I could create tables which make my difference in means clear to the reader. As of this time, I am still working n DVS-7. In terms of program efficiency, I used the summarize() function as well as dplyr in Lab 5 which demonstrate how I use modern tools to write functions which increase the efficiency of my code. I am still working on PE-1 and PE-3. In terms of DSM-1 to DSM-3 I am still learning the material.

In terms of revised thinking, I have generally taken advantage of the one-week limit of the revision submissions. From Challenge 3, I learned to have concise code as well as to not have warning messages show up when data is being read, which I have applied to current assignments.

In terms of extending thinking, I have done all of the Challenges so far, and I believe that with Challenge 4 I have definitely grown my abilities in R.

In terms of being a collaborative group member, I have been present for all of the lectures and ask questions for my team members when necessary. I complete all of the preview activities to make sure I don't hold back my team. However, I am either slightly or very late for a large percentage of my labs and challenges which I hope to change in order to raise my grade up to an A.

In terms of peer-code review, I have been slacking off when it comes to reviewing my classmates' code so I hope to change that in the upcoming weeks.
