---
title: "Challenge 4"
author: "Allen Choi"
format:
  html:
    toc: true
    code-fold: true
    number-sections: true
    self-contained: true
editor: visual
theme: cerulean
execute:
  error: true
  echo: true
---

```{r setup}
#| warning: false
#| include: false
library(tidyverse)
library(here)
library(readxl)
library(lubridate)
```

# Housing Data read-in

```{r}
#| warning: false
# Thank you to the California Association of Realtors:
# https://www.car.org/marketdata/data/housingdata
dirtyhousing <- readxl::read_xls(here::here("supporting_artifacts", "extended_learning", "Data",
  "MedianPricesofExistingDetachedHomesHistoricalData.xls"), skip = 7)
```

# Wrangling Housing Data

```{r}
uniqueid = 1:16
# We only need data from 2015 through 2018 so we need to remove all other data.
housing <- dirtyhousing |> 
  mutate(Year = year(ymd(`Mon-Yr`)),
         Month = month(ymd(`Mon-Yr`))) |> 
  filter(Year == 2015 | Year == 2016 | 
         Year == 2017 | Year == 2018) |> 
# We need to make sure the column names on both datasets match.
  
  select(Year, `Los Angeles`, Sacramento, 
         `San Diego`, `San Francisco`)|> 
  rename(LosAngeles = `Los Angeles`,
         SanDiego = `San Diego`,
         SanFrancisco = `San Francisco`) |> 
  pivot_longer(-c(Year)) |> # Thank you https://stackoverflow.com/a/65704983
  
# Taking means of medians by year
  group_by(name, Year) |> 
  mutate(MeanYearly = mean(value),
         Year = as.character(Year)) |> 
  distinct(Year, .keep_all = TRUE) |> 
  rename(region = name)

```

# California Avocado Data

```{r data}
#| warning: false
avocados <- read_csv(here::here("supporting_artifacts", "extended_learning", "Data", "avocado.csv"), 
                     show_col_types = FALSE)

cal_region_data <- tibble(
  region = c("LosAngeles", "SanDiego", "Sacramento", "SanFrancisco"))

ca_avocados <- semi_join(avocados, cal_region_data) |>
  separate(col = Date, into = c("Year", "Month", "Day"), sep = "-") |> 
  group_by(Year, Month, region) |> 
  mutate(TotalSales = AveragePrice * `Total Volume`) |> 
  group_by(Year, region) |> 
  mutate(AvgYearlySales = mean(TotalSales)) |> 
  distinct(AvgYearlySales, .keep_all = TRUE) |> 
  select(Year, region, AvgYearlySales)
  

```

# Joining the two together

```{r}
housingavocado <- left_join(housing, ca_avocados)
housingavocado |> 
  ggplot(mapping = aes(x = AvgYearlySales, y = MeanYearly, col = region)) +
  geom_point() +
  scale_x_continuous(limits = c(0, 2000000)) +
  scale_y_continuous(limits = c(0, 2000000)) +
  labs(x = "Average Yearly Avocado Sales",
       y = "Average Yearly House Cost",
       title = "Avocado Consumption vs. Cost of Homes") +
  theme(legend.position = "none") +
  annotate("text", y = 300000, x = 550000, label = "Sacramento") +
  annotate("text", y = 570000, x = 500000, label = "San Diego") +
  annotate("text", y = 1350000, x = 850000, label = "San Francisco") +
  annotate("text", y = 500000, x = 1850000, label = "Los Angeles") 
  
```

As we can conclude from the graph, there is no clear correlation between avocado sales and home prices. However, it does seem that within cities, an increase in avocado sales does seem loosely related to home prices.
