---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

A key area that I grew in was specifically using dplyr to manipulate data in order to get the statistics that I needed. To be more specific, I am able to more easily use mutates and pivots in order to get the data in a format that I need to get the statistics that I want. A key example of this is in Challenge 4 where I found a csv file online containing housing data that I wanted. I had to identify which statistics my analysis needed, and had to work backwards from there. dplyr was used to eliminate most of the unnecessary information, renames were used to match variable names across the two datasets, and pivots were used in order to group and find the mean of the data. Finally, by using joins, I was able to combine a dataset that I used in Lab 4 with a cleaned dataset of mean housing prices in California. I also feel like my ability to effectively communicate data to other people increased greatly. In Lab 5, I was able to change the factor levels of a variable in order to have the days of the week shown in the appropriate order in the graph. This makes it much more easier see at a glance what the data is trying to show.
